version: "3.7"
services:
  jenkins:
    image: jenkins-test:1.1
    build:
      context: .
    ports:
      - "8080:8080"
      - "3333:3333"
      # - "500:50000"
      - "5000:50000" # port 50000 on Windows causes Error starting userland proxy: Bind for 0.0.0.0:50000: unexpected error Permission denied
    networks:
      - authentication
    environment:
      VIRTUAL_HOST: "jenkins.inspo.test"
      VIRTUAL_PORT: 8080
    volumes:
      - data:/var/jenkins_home
volumes:
  data:
networks:
  authentication:
